const localizacao = {
    "Alemanha": [
        "Berlim",
        "Bielefeld",
        "Bochum",
        "Bona",
        "Bremen",
        "Colónia",
        "Dortmund",
        "Dresden",
        "Duisburgo",
        "Düsseldorf",
        "Estugarda",
        "Essen",
        "Frankfurt",
        "Hamburgo",
        "Hannover",
        "Leipzig",
        "Mannheim",
        "Munique",
        "Nuremberga",
        "Wuppertal"
    ],
    
    "Áustria": [
        "Viena",
        "Graz",
        "Linz",
        "Salzburgo",
        "Innsbruck",
        "Klagenfurt",
        "Villach",
        "Wels",
        "Sankt Pölten",
        "Dornbirn"
    ],
    "Bélgica": [
        "Bruxelas",
        "Antuérpia",
        "Gante",
        "Charleroi",
        "Liège",
        "Bruges",
        "Namur",
        "Leuven",
        "Mons",
        "Aalst"
    ],
    "Bulgária": [
        "Sófia",
        "Plovdiv",
        "Varna",
        "Burgas",
        "Ruse",
        "Stara Zagora",
        "Pleven",
        "Sliven",
        "Dobrich",
        "Shumen"
    ],
    "Chipre": [
        "Nicósia",
        "Limassol",
        "Larnaca",
        "Famagusta",
        "Pafos",
        "Kyrenia",
        "Protaras",
        "Morphou",
        "Aradippou",
        "Paralimni"
    ],
    "Croácia": [
        "Zagrebe",
        "Split",
        "Rijeka",
        "Osijek",
        "Zadar",
        "Pula",
        "Slavonski Brod",
        "Karlovac",
        "Varaždin",
        "Šibenik"
    ],
    "Dinamarca": [
        "Copenhaga",
        "Aarhus",
        "Odense",
        "Aalborg",
        "Esbjerg",
        "Randers",
        "Kolding",
        "Horsens",
        "Vejle",
        "Roskilde"
    ],
    "Eslováquia": [
        "Bratislava",
        "Košice",
        "Prešov",
        "Žilina",
        "Banská Bystrica",
        "Nitra",
        "Trnava",
        "Trenčín",
        "Martin",
        "Poprad"
    ],
    "Eslovénia": [
        "Liubliana",
        "Maribor",
        "Celje",
        "Kranj",
        "Velenje",
        "Koper",
        "Novo Mesto",
        "Ptuj",
        "Trbovlje",
        "Kamnik"
    ],
    "Espanha": [
        "Madrid",
        "Barcelona",
        "Valência",
        "Sevilha",
        "Saragoça",
        "Málaga",
        "Múrcia",
        "Palma de Maiorca",
        "Las Palmas",
        "Bilbau"
    ],
    "Estónia": [
        "Talim",
        "Tartu",
        "Narva",
        "Pärnu",
        "Kohtla-Järve",
        "Viljandi",
        "Rakvere",
        "Maardu",
        "Kuressaare",
        "Sillamäe"
    ],
    "Finlândia": [
        "Helsínquia",
        "Espoo",
        "Tampere",
        "Vantaa",
        "Oulu",
        "Turku",
        "Jyväskylä",
        "Lahti",
        "Kuopio",
        "Pori"
    ],
    "França": [
        "Paris",
        "Marselha",
        "Lyon",
        "Toulouse",
        "Nice",
        "Nantes",
        "Estrasburgo",
        "Montpellier",
        "Bordéus",
        "Lille"
    ],
    "Grécia": [
        "Atenas",
        "Salónica",
        "Patras",
        "Heraclião",
        "Larissa",
        "Volos",
        "Rodes",
        "Ioannina",
        "Chania",
        "Agrinio"
    ],
    "Hungria": [
        "Budapeste",
        "Debrecen",
        "Szeged",
        "Miskolc",
        "Pécs",
        "Győr",
        "Nyíregyháza",
        "Kecskemét",
        "Székesfehérvár",
        "Szombathely"
    ],
    "Irlanda": [
        "Dublin",
        "Cork",
        "Limerick",
        "Galway",
        "Waterford",
        "Drogheda",
        "Dundalk",
        "Swords",
        "Bray",
        "Navan"
    ],
    "Itália": [
        "Roma",
        "Milão",
        "Nápoles",
        "Turim",
        "Palermo",
        "Génova",
        "Bolonha",
        "Florença",
        "Bari",
        "Catania"
    ],
    "Letónia": [
        "Riga",
        "Daugavpils",
        "Liepāja",
        "Jelgava",
        "Jūrmala",
        "Ventspils",
        "Rēzekne",
        "Valmiera",
        "Ogre",
        "Tukums"
    ],
    "Lituânia": [
        "Vilnius",
        "Kaunas",
        "Klaipėda",
        "Šiauliai",
        "Panevėžys",
        "Alytus",
        "Marijampolė",
        "Mažeikiai",
        "Jonava",
        "Utena"
    ],
    "Luxemburgo": [
        "Luxemburgo",
        "Esch-sur-Alzette",
        "Differdange",
        "Dudelange",
        "Ettelbruck",
        "Diekirch",
        "Wiltz",
        "Rumelange",
        "Grevenmacher",
        "Remich"
    ],
    "Malta": [
        "Valeta",
        "Birkirkara",
        "Mosta",
        "Qormi",
        "Żabbar",
        "San Pawl il-Baħar",
        "Sliema",
        "Żejtun",
        "Fgura",
        "Żebbuġ"
    ],
    "Países Baixos": [
        "Amesterdão",
        "Roterdão",
        "Haia",
        "Utrecht",
        "Eindhoven",
        "Groninga",
        "Tilburgo",
        "Almere",
        "Breda",
        "Nimega"
    ],
    "Polónia": [
        "Varsóvia",
        "Cracóvia",
        "Łódź",
        "Vratislávia",
        "Poznań",
        "Gdańsk",
        "Szczecin",
        "Bydgoszcz",
        "Lublin",
        "Katowice"
    ],
    "Portugal": [
        "Lisboa",
        "Porto",
        "Vila Nova de Gaia",
        "Braga",
        "Amadora",
        "Coimbra",
        "Funchal",
        "Almada",
        "Setúbal",
        "Aveiro"
    ],
    "República Checa": [
        "Praga",
        "Brno",
        "Ostrava",
        "Plzeň",
        "Liberec",
        "Olomouc",
        "Ústí nad Labem",
        "České Budějovice",
        "Hradec Králové",
        "Pardubice"
    ],
    "Roménia": [
        "Bucareste",
        "Cluj-Napoca",
        "Timișoara",
        "Iași",
        "Constanța",
        "Craiova",
        "Brașov",
        "Galați",
        "Ploiești",
        "Oradea"
    ],
    "Suécia": [
        "Estocolmo",
        "Gotemburgo",
        "Malmo",
        "Upsália",
        "Västerås",
        "Örebro",
        "Linköping",
        "Helsingborg",
        "Jönköping",
        "Norrköping"
    ]
};